version: '3.8'

services:
  ompeak-app:
    image: ompeak-project:latest
    container_name: ompeak-project
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ompeak-network

  nginx:
    image: nginx:alpine
    container_name: ompeak-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ompeak-app
    restart: unless-stopped
    networks:
      - ompeak-network

networks:
  ompeak-network:
    driver: bridge